
spring:
  application:
    name: gmall-eureka-zuul   #配置应用名字（ServiceId）

eureka:
  instance:
    hostname: localhost       #配置主机地址
    instance-id: eureka-zuul-8070   # 服务名称,实例id (InstanceId)
    prefer-ip-address: true  #访问路劲可以显示ip地址
  client:
    service-url:    #设置与Eureka 服务端交互的地址
      defaultZone: http://localhost:7001/eureka/
server:
  port: 8070
zuul:
  routes:
    myprovider.serviceId: gmall-eureka-provider   #配置访问映射规则
    myprovider.path: /myprovider/**
  ignored-services: gmall-eureka-provider   #原来的访问不了    多个可以用"*"
  # prefix:  还可以配置前缀